export function isTextType(mimeType) {
  return /^text\/|^application\/(javascript|json)/.test(mimeType);
}

export const MIME_TYPES = {
  js: 'text/javascript',
  json: 'application/json',
  wasm: 'application/wasm',
  css: 'text/css',
  html: 'text/html',
  htm: 'text/html',
  xml: 'text/xml',
  txt: 'text/plain',
  gif: 'image/gif',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  png: 'image/png',
  svg: 'image/svg+xml',
  webp: 'image/webp',
  ico: 'image/x-icon',
  bmp: 'image/x-ms-bmp',
  tif: 'image/tiff',
  tiff: 'image/tiff',
  mp3: 'audio/mpeg',
  ogg: 'audio/ogg',
  m4a: 'audio/x-m4a',
  m3u8: 'application/vnd.apple.mpegurl',
  mp4: 'video/mp4',
  webm: 'video/webm',
  flv: 'video/x-flv',
  mpeg: 'video/mpeg',
  mpg: 'video/mpeg',
  mov: 'video/quicktime',
  avi: 'video/x-msvideo',
  wmv: 'video/x-ms-wmv',
  woff: 'font/woff',
  woff2: 'font/woff2',
  ttf: 'font/ttf',
  pdf: 'application/pdf',
};
